# Generated by Django 4.2.3 on 2023-07-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rename_price_house_price_per_night_house_pet_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='pet_allowed',
        ),
        migrations.AddField(
            model_name='house',
            name='pets_allowed',
            field=models.BooleanField(default=True, help_text='Dose this house allow pets?', verbose_name='Pets Allowed?'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_per_night',
            field=models.PositiveIntegerField(help_text='Enter Only Positive Numbers per Night', verbose_name='Price'),
        ),
    ]
