# Generated by Django 4.2.3 on 2023-08-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
