# Generated by Django 4.2.3 on 2023-08-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='experience_time',
        ),
    ]
